<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
	<DocumentationFile>bin\Debug\net6.0\Defra.PTS.Pet.Functions.xml</DocumentationFile>
	<GenerateDocumentationFile>False</GenerateDocumentationFile>
	<OutputType>Exe</OutputType>
	<ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Defra.Trade.Common.Api" Version="2.0.5" />
    <PackageReference Include="Defra.Trade.Common.Functions" Version="2.7.2" />
    <PackageReference Include="Defra.Trade.Common.Security" Version="2.0.5" />
    <PackageReference Include="Defra.Trade.Common.Soc" Version="1.1.16" />
    <PackageReference Include="Defra.Trade.Common.Sql" Version="2.0.3" />
    <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.1.0" />
    <PackageReference Include="System.Data.SqlClient" Version="4.8.6" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.3.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore" Version="1.3.3" />
    <PackageReference Include="AutoMapper" Version="16.1.1" />
    <PackageReference Include="Azure.Storage.Blobs" Version="12.29.0-beta.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Defra.PTS.Pet.ApiServices\Defra.PTS.Pet.ApiServices.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
	  <None Update="local.settings.json">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		  <CopyToPublishDirectory>Never</CopyToPublishDirectory>
	  </None>
  </ItemGroup>
  <ItemGroup>
    <Using Include="System.Threading.ExecutionContext" Alias="ExecutionContext" />
  </ItemGroup>
</Project>
