<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.1" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.3.9" />
    <PackageReference Include="System.Security.Cryptography.Xml" Version="11.0.0-preview.3.26207.106" />
  </ItemGroup>

</Project>
